---
AWSTemplateFormatVersion: '2010-09-09'
Description: A test stack for demonstrating Cloudformation
Parameters:
  Subnet:
    Description: Subnet in which to place the resources
    Type: AWS::EC2::Subnet::Id
    # this type is not that helpful, since it just shows IDs
  VPC:
    Description: VPC in which to put the EC2 instance
    Type: AWS::EC2::VPC::Id
  InstanceType:
    Description: The instance type for the Launch Config
    Type: String
    Default: t3.micro
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
  AMI:
    Description: a reference to the AMI you want
    Type: AWS::EC2::Image::Id
    Default: ami-0b0dcb5067f052a63
Resources:
  SecurityGroupHTTPFromWorld:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows port 80 from the world
      GroupName: !Sub 'HTTPFromWorld-${AWS::StackName}'
      # If we do not specify egress, the default 
      # "all traffic" egress rule will be created.
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: HTTPFromWorld
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          sudo amazon-linux-extras install -y nginx1
          sudo service nginx start
      ImageId: !Ref AMI
      InstanceType:
        Ref: InstanceType
      SecurityGroupIds:
        - !GetAtt SecurityGroupHTTPFromWorld.GroupId
      SubnetId:
        Ref: Subnet
      Tags:
        - Key: Name
          Value: MyNginxInstance
Outputs:
  InstanceIP:
    Description: The public IP of the instance
    Value: !GetAtt MyInstance.PublicIp
