AWSTemplateFormatVersion: 2010-09-09
Description: A simple CloudFormation template
Resources:
    MyBucket3:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: '{{resolve:ssm:MyBucketNameParameter}}sadfasfasdfasf'
    MyBucket4:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: '{{resolve:secretsmanager:MyBucketSecret2:SecretString:bucketname}}'