AWSTemplateFormatVersion: 2010-09-09
Description: Simple VPC and Subnet creation
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: DeleteThisVPC
  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: DeleteThisSubnet
Outputs:
  VPCID:
    Description: the ID of this VPC
    Value: !Ref MyVPC

